FORMAT: 1A
HOST: https://api.patientbond.com/aha

# CarePlan API

The CarePlan API allows consumers to submit a Health Motivation Assessment to view
their Health Report and generate a CarePlan tailored to their specific health goals
and psychographic profile.

## Authorization [/token]

The API uses OAuth 2.0 for authentication. Authorized users are granted a service
account and use the associated credentials to request an access token. Applications
must include a cryptographically-signed JSON Web Token in any request for an access
token. This token can then be used to make authorized API calls.

See [Google OAuth 2.0](https://developers.google.com/identity/protocols/OAuth2ServiceAccount)
documentation for more information.

### Request Access Token [POST]

+ Request (application/x-www-form-urlencoded)

        grant_type=password&username=sbench66Ix52&password=5O22188wdahw
    
+ Response 200 (application/json;charset=UTF-8)

        {
            "access_token": "-01ZFJy10rkMkeAzRukrTcPqpB9WnNslI3iKPm7AMPdqISO0wMLCbEij5u2qxHnkE6hl-J0vwzvA8Jv13RggsGu2PH4pFFfUBMDNDoDwFlmwVwVfCiCeS4tCDbDuJyKQKXrgPgOHHhKKiQK_zQ6sjGEdv4plfA6s6RFriMilLjvlWGLN6rm-PFoeA0zvsqHL5tU9-h-LSsbPQ-YtHxFQ-_oi_n-YC6XbvZ7P2Gd-owc-23Yf_edUvOKIeXhVQ2VLXkOP8Zu6q8lkgOrYpcNdi_0U8fNhwv5roLzqIZZm5YE",
            "token_type": "bearer",
            "expires_in": 3599
        }

## Assessment [/assessment]

### Get Health Motivation Assessment Questions [GET /assessment/{version}]

Returns the specified version of the Health Motivation Assessment question set. If no version is specified, the current version of the Health Motivation Assessment is returned.

+ Request

    + Headers
    
            Accept: application/json
            Accept-Language: en-US, en
            Authorization: Bearer mF_9.B5f-4.1JqM

+ Parameters

    + version: `v1` (string, optional) - Version of a Health Motivation Assessment.

+ Response 200 (application/json)

        {
            "version": "v1",
            "content": [
                {
                    "question": "How tall are you?",
                    "subheading": "CALCULATING YOUR BMI",
                    "response": {
                        "type": "number",
                        "minimum": 24,
                        "maximum": 96,
                        "unit": "inches"
                    }
                },
                {
                    "question": "How much do you weigh?",
                    "subheading": "CALCULATING YOUR BMI",
                    "response": {
                        "type": "number",
                        "minimum": 48, 
                        "maximum": 999,
                        "unit": "pounds"
                    }
                },
                {
                    "question": "Are you pregnant or breastfeeding?",
                    "response": {
                        "type": "radio",
                        "choices": [
                            "Yes",
                            "No"
                        ]
                    }
                },
                {
                    "question": "What is your smoking status?",
                    "response": {
                        "type": "radio",
                        "choices": [
                            "I currently smoke.",
                            "I quit in the last 12 months.",
                            "I quit more than 12 months ago.",
                            "I have never been a smoker."
                        ]
                    }
                },
                {
                    "question": "Do you have diabetes?",
                    "response": {
                        "type": "radio",
                        "choices": [
                            "Yes",
                            "No"
                        ]
                    }
                },
                {
                    "question": "Have you ever been diagnosed with any of the following:",
                    "subheading": "Heart attack, Heart failure, Stroke/TIA, Vascular disease, Congenital heart defects, Coronary heart diseases/chest pain", 
                    "response": {
                        "type": "radio",
                        "choices": [
                            "Yes",
                            "No"
                        ]
                    }
                },
                {
                    "question": "How much physical activity do you get each week?",
                    "response": [
                        {
                            "title": "Very Light",
                            "type": "number",
                            "minimum": 0,
                            "step": 5,
                            "unit": "minutes"
                        },
                        {
                            "title": "Light",
                            "type": "number",
                            "minimum": 0,
                            "step": 5,
                            "unit": "minutes"
                        },
                        {
                            "title": "Moderate",
                            "type": "number",
                            "minimum": 0,
                            "step": 5,
                            "unit": "minutes"
                        },
                        {
                            "title": "Vigorous",
                            "type": "number",
                            "minimum": 0,
                            "step": 5,
                            "unit": "minutes"
                        }
                    ]
                },
                {
                    "question": "RATE THIS STATEMENT",
                    "subheading": "I believe that I can directly influence how long I will live, regardless of my family history.",
                    "response": {
                        "type": "radio",
                        "choices": [
                            "Strongly Agree",
                            "Agree",
                            "Neither Agree Nor Disagree",
                            "Disagree",
                            "Strongly Disagree"
                        ]
                    }
                },
                {
                    "question": "RATE THIS STATEMENT",
                    "subheading": "I'm more worried about other family members' health than my own.",
                    "response": {
                        "type": "radio",
                        "choices": [
                            "Strongly Agree",
                            "Agree",
                            "Neither Agree Nor Disagree",
                            "Disagree",
                            "Strongly Disagree"
                        ]
                    }
                },
                {
                    "question": "RATE THIS STATEMENT",
                    "subheading": "I prefer alternative medicine to standard medical practice.",
                    "response": {
                        "type": "radio",
                        "choices": [
                            "Strongly Agree",
                            "Agree",
                            "Neither Agree Nor Disagree",
                            "Disagree",
                            "Strongly Disagree"
                        ]
                    }
                },
                {
                    "question": "Please indicate how much you agree or disagree with the following statement regarding health and wellness",
                    "subheading": "I believe alternative/holistic/natural medicines are effective for helping maintain my health and wellbeing.",
                    "response": {
                        "type": "radio",
                        "choices": [
                            "Strongly Agree",
                            "Agree",
                            "Neither Agree Nor Disagree",
                            "Disagree",
                            "Strongly Disagree"
                        ]
                    }
                },
                {
                    "question": "How many cups of vegetables do you eat in an average day?",
                    "response": {
                        "type": "number",
                        "minimum": 0,
                        "step": 1,
                        "unit": "cups"
                    }
                },
                {
                    "question": "How many cups of fruits do you eat in an average day?",
                    "response": {
                        "type": "number",
                        "minimum": 0, 
                        "step": 1
                        "unit": "cups"
                    }
                },
                {
                    "question": "How many servings of whole grains do you eat in an average day?",
                    "response": {
                        "type": "number",
                        "minimum": 0, 
                        "step": 1
                        "unit": "servings"
                    }
                },
                {
                    "question": "How many 12 oz beverages with added sugars do you drink every week?",
                    "response": {
                        "type": "number",
                        "minimum": 0, 
                        "step": 1
                        "unit": "servings"
                    }
                },
                {
                    "question": "EVALUATE THIS STATEMENT",
                    "subheading": "I avoid prepackaged and processed foods.",
                    "response": {
                        "type": "radio",
                        "choices": [
                            "Yes",
                            "No"
                        ]
                    }
                },
                {
                    "question": "EVALUATE THIS STATEMENT",
                    "subheading": "I rarely eat out, but when I do, I seek out lower sodium options.",
                    "response": {
                        "type": "radio",
                        "choices": [
                            "Yes",
                            "No"
                        ]
                    }
                },
                {
                    "question": "EVALUATE THIS STATEMENT",
                    "subheading": "I avoid salt when I'm cooking at home.",
                    "response": {
                        "type": "radio",
                        "choices": [
                            "Yes",
                            "No"
                        ]
                    }
                },
                {
                    "question": "RATE THIS STATEMENT",
                    "subheading": "I don't let being sick get in the way of my work.",
                    "response": {
                        "type": "radio",
                        "choices": [
                            "Strongly Agree",
                            "Agree",
                            "Neither Agree Nor Disagree",
                            "Disagree",
                            "Strongly Disagree"
                        ]
                    }
                },
                {
                    "question": "RATE THIS STATEMENT",
                    "subheading": "There are better things in life to focus on than healthy behavior.",
                    "response": {
                        "type": "radio",
                        "choices": [
                            "Strongly Agree",
                            "Agree",
                            "Neither Agree Nor Disagree",
                            "Disagree",
                            "Strongly Disagree"
                        ]
                    }
                },
                {
                    "question": "RATE THIS STATEMENT",
                    "subheading": "I am successful in maintaining healthy nutritional habits.",
                    "response": {
                        "type": "radio",
                        "choices": [
                            "Strongly Agree",
                            "Agree",
                            "Neither Agree Nor Disagree",
                            "Disagree",
                            "Strongly Disagree"
                        ]
                    }
                },
                {
                    "question": "RATE THIS STATEMENT",
                    "subheading": "I will go to the doctor at the first sign of health concerns.",
                    "response": {
                        "type": "radio",
                        "choices": [
                            "Strongly Agree",
                            "Agree",
                            "Neither Agree Nor Disagree",
                            "Disagree",
                            "Strongly Disagree"
                        ]
                    }
                },
                {
                    "question": "CHECK ALL THAT APPLY",
                    "subheading": "I take medication to:",
                    "response": {
                        "type": "checkbox",
                        "choices": [
                            "Lower my blood pressure",
                            "Lower my cholesterol",
                            "Lower my blood sugar"
                        ]
                    }
                },
                {
                    "question": "What's your blood pressure?",
                    "subheading": "SYSTOLIC (TOP NUMBER)",
                    "response": {
                        "type": "radio",
                        "choices": [
                            [
                                {
                                    "type": "number",
                                    "minimum": 90,
                                    "maximum": 210, 
                                    "step": 1,
                                    "unit": "mmHg"
                                },
                                "I don't know this number"
                            ]
                        ]
                    }
                },    
                {
                    "question": "What's your blood pressure?",
                    "subheading": "DIASTOLIC (TOP NUMBER)",
                    "response": {
                        "type": "radio",
                        "choices": [
                            [
                                {
                                    "type": "number",
                                    "minimum": 50,
                                    "maximum": 210, 
                                    "step": 1,
                                    "unit": "mmHg"
                                },
                                "I don't know this number"
                            ]
                        ]
                    }
                },  
                {
                    "question": "What's your blood cholesterol?",
                    "response": {
                        "type": "radio",
                        "choices": [
                            [
                                {
                                    "type": "number",
                                    "minimum": 40,
                                    "maximum": 400, 
                                    "step": 1,
                                    "unit": "mg/dL"
                                },
                                "I don't know this number"
                            ]
                        ]
                    }
                },  
                {
                    "question": "What's your blood sugar (fasting)?",
                    "response": {
                        "type": "radio",
                        "choices": [
                            [
                                {
                                    "type": "number",
                                    "minimum": 50,
                                    "maximum": 500, 
                                    "step": 1,
                                    "unit": "mg/dL"
                                },
                                "I don't know this number"
                            ]
                        ]
                    }
                },  
                {
                    "question": "RATE THIS STATEMENT",
                    "subheading": "My doctor is the most credible authority for my health & wellness needs.",
                    "response": {
                        "type": "radio",
                        "choices": [
                            "Strongly Agree",
                            "Agree",
                            "Neither Agree Nor Disagree",
                            "Disagree",
                            "Strongly Disagree"
                        ]
                    }
                },
                {
                    "question": "RATE THIS STATEMENT",
                    "subheading": "I actively seek information about nutrition and healthy diets.",
                    "response": {
                        "type": "radio",
                        "choices": [
                            "Strongly Agree",
                            "Agree",
                            "Neither Agree Nor Disagree",
                            "Disagree",
                            "Strongly Disagree"
                        ]
                    }
                },
                {
                    "question": "RATE THIS STATEMENT",
                    "subheading": "I'm willing to experience major delays in seeing a doctor if it meant everyone could get the health care they need.",
                    "response": {
                        "type": "radio",
                        "choices": [
                            "Strongly Agree",
                            "Agree",
                            "Neither Agree Nor Disagree",
                            "Disagree",
                            "Strongly Disagree"
                        ]
                    }
                },
                {
                    "question": "RATE THIS STATEMENT",
                    "subheading": "I give a significant amount of money to charity.",
                    "response": {
                        "type": "radio",
                        "choices": [
                            "Strongly Agree",
                            "Agree",
                            "Neither Agree Nor Disagree",
                            "Disagree",
                            "Strongly Disagree"
                        ]
                    }
                }
            ]
        }        

### Create a Health Report [POST]

Allows users to submit their Health Motivation Assessment and returns a health score, a Life Simple 7 success plan, the user's psychographic profile, and up to 3 AHA-recommended goals.

+ Request (application/json)

    + Headers
    
            Accept: application/json
            Accept-Language: en-US, en
            Authorization: Bearer mF_9.B5f-4.1JqM

    + Attributes
    
        + content
            + activities
                + smokingStatus (enum[string]) - Current smoking status of user
                    
                    + Members
                        + `active` - User currently smokes
                        + `stopped` - User quit in the last 12 months
                        + `quit` - User quit more than 12 months ago
                        + `never` - User has never been a smoker

    + Body
    
            {
                "version": "v1",
                "content": {
                    "activities": {
                        "height": 67,
                        "weight": 140,
                        "pregnant/breastfeeding": false,
                        "smokingStatus": "active",
                        "diabetes": true,
                        "conditions": true,
                        "physicalActivity": {
                            "veryLight": 30,
                            "light": 30,
                            "moderate": 30,
                            "vigorous": 30
                        }
                    },
                    "diet": {
                        "vegetables": 4,
                        "fruits": 4,
                        "wholeGrains": 4,
                        "sugarBeverages": 4,
                        "avoidProcessedFoods": false,
                        "avoidEatingOut": false,
                        "avoidSalt": false
                    },
                    "health": [
                        {
                          "systolicBP": 121,
                          "diastolicBP": 123,
                          "dontknow": false,
                          "medication": false
                        },
                        {
                          "bloodCholesterol": 123,
                          "dontknow": false,
                          "medication": false
                        },
                        {
                          "bloodSugar": 123,
                          "dontknow": false,
                          "medication": false
                        }
                    ],
                    "psychographic": {
                        "influenceHowLongIWillLive": 3,
                        "worriedAboutFamilyHealth": 2,
                        "preferAlternativeMedicine": 1,
                        "holisticMedicinesEffective": 1,
                        "dontLetSickGetInWayOfWork": 5,
                        "betterThingsThanHealth": 3,
                        "successfulHealthyNutritionHabits": 2,
                        "goToDoctorAtFirstSign": 1,
                        "doctorMostCredibleAuthority": 2,
                        "activelySeekInfoDietNutrition": 3,
                        "willingDelayForOthers": 3,
                        "giveSignificantMoneyToCharity": 3
                    }
                }
            }


+ Response 200 (application/json)

        {
            "profile": "willful_endurer",
            "results": {
                "positive": [
                    {
                        "focus": "smoking",
                        "value": "never",
                        "recommended": "never",
                        "unit": null,
                        "summary": "Smoking is the most important preventable cause of premature death in the United States."
                    },
                    {
                        "focus": "diet",
                        "value": {
                            "fruit": 5,
                            "vegetables": 6,
                            "wholeGrain": 3
                        },
                        "recommended": {
                            "fruit": 5,
                            "vegetables": 5,
                            "wholeGrain": 4
                        },
                        "unit": "servings",
                        "summary": "A healthy diet and lifestyle are your best weapons to fight cardiovascular disease."
                    },
                    {
                        "focus": "cholesterol",
                        "value": 180,
                        "recommended": {
                            "low": 80,
                            "healthy": 120,
                            "high": 200,
                            "max": 240
                        },
                        "unit": "mg/dL",
                        "summary": "Too much bad cholesterol forms plaque in your veins and arteries, which can lead to heart disease and stroke."
                    },
                    {
                        "focus": "bloodPressure",
                        "value": {
                            "systolic": 110,
                            "diastolic": 70
                        },
                        "recommended": {
                            "low": {
                                "systolic": 60,
                                "diastolic": 40
                            },
                            "high": {
                                "systolic": 120,
                                "diastolic": 80
                            }
                        },
                        "unit": "mmHg",
                        "summary": "High blood pressure increases the risk of stroke, heart attack, kidney disease, and loss of brain function."
                    },
                ],
                "negative": [
                    {
                        "focus": "exercise",
                        "value": 15,
                        "recommended": {
                            "low": 0,
                            "high": 60
                        },
                        "unit": "min/day",
                        "summary": "Exercising for at least 30 minutes a day can drastically improve overall vascular health."
                    },
                    {
                        "focus": "bmi",
                        "value": 27,
                        "recommended": {
                            "low": 12,
                            "healthy": 18,
                            "high": 24,
                            "max": 30
                        },
                        "unit": null,
                        "summary": "Too much fat puts you at higher risk for health problems such as high blood pressure, high blood cholesterol, and diabetes."
                    },
                    {
                        "focus": "bloodSugar",
                        "value": 150,
                        "recommended": {
                            "low": 100,
                            "healthy": 120,
                            "high": 140,
                            "max": 160
                        },
                        "unit": "mg/Dl",
                        "summary": "Maintaining a healthy body weight, following a healthy eating plan, and doing physical activity regularly can maintain a healthy blood sugar level."
                    },
                ]
            },
            "recommendations": [
                {
                    "focus": "exercise",
                    "goals": [
                        {
                            "goalID": "increaseWorkoutLength",
                            "description": "Increase the length of my workouts",
                            "summary": "Increase workout length",
                        },
                        {
                            "goalID": "increaseWorkoutIntensity",
                            "description": "Increase the intensity of my workouts",
                            "summary": "Increase workout intensity",
                        },
                        {
                            "goalID": "loseWeight",
                            "description": "Lose 5% of my total body weight",
                            "summary": "Lose 5% body weight",
                        }
                    ],
                },
                {
                    "focus": "bloodSugar",
                    "goals": [
                        {
                            "goalID": "reduceSugar",
                            "description": "Reduce sugar intake",
                            "summary": "Reduce sugar intake",
                        },
                        {
                            "goalID": "loseWeight",
                            "description": "Lose 5% of my total body weight",
                            "summary": "Lose 5% body weight",
                        }
                    ],
                },
                {
                    "focus": "bmi",
                    "goals": [
                        {
                            "goalID": "reduceSugar",
                            "description": "Reduce sugar intake",
                            "summary": "Reduce sugar intake",
                        },
                        {
                            "goalID": "loseWeight",
                            "description": "Lose 5% of my total body weight",
                            "summary": "Lose 5% body weight",
                        }
                    ]
                }
            ]
        }

## Goals [/goals]

### Create a New CarePlan [POST]

Creates a new CarePlan based on the goals passed in the request.

+ Request (application/json)

    + Headers
    
            Accept: application/json
            Accept-Language: en-US, en
            Authorization: Bearer mF_9.B5f-4.1JqM
            
    + Body
    
            {
                "profile": "willful_endurer",
                "goals": [
                    {
                        "focus": "glucose",
                        "goalID": "reduceSugar"
                    } ,
                ]
            }


+ Response 200 (application/json)

        {
            "profile": "willful_endurer",
            "goals": [
                {
                    "focus": "bloodSugar",
                    "goal": "reduceSugar",
                    "frequency": 7,
                    "checkpoint": {
                        "prompt": "What did you eat today?",
                        "response": [
                            {
                                "title": "Breakfast",
                                "type": "text",
                            },
                            {
                                "title": "Lunch",
                                "type": "text",
                            },
                            {
                                "title": "Dinner",
                                "type": "text",
                            },
                            {
                                "title": "Snack",
                                "type": "text",
                            },
                        ],
                        "feedback": {
                            "behind": [
                                {
                                    "title": "Keep at it!",
                                    "description": "Reducing the amount of sugar you consume helps to lower your blood sugar!",
                                },
                            ],
                            "on_schedule": [
                                {
                                    "title": "Great job!",
                                    "description": "You are on the right track to reducing your blood sugar!",
                                },
                            ],
                        },
                    },
                },
                {
                    "focus": "exercise",
                    "goal": "increaseWorkoutIntensity",
                    "frequency": 2,
                    "checkpoint": {
                        "prompt": "What kind(s) of exercise did you do this week?",
                        "response": [
                            {
                                "title": "Very Light",
                                "type": "number",
                                "minimum": 0,
                                "step": 5,
                                "unit": "minutes"
                            },
                            {
                                "title": "Light",
                                "type": "number",
                                "minimum": 0,
                                "step": 5,
                                "unit": "minutes"
                            },
                            {
                                "title": "Moderate",
                                "type": "number",
                                "minimum": 0,
                                "step": 5,
                                "unit": "minutes"
                            },
                            {
                                "title": "Vigorous",
                                "type": "number",
                                "minimum": 0,
                                "step": 5,
                                "unit": "minutes"
                            },
                        ],
                        "feedback": {
                            "behind": [
                                {
                                    "title": "Keep at it!",
                                    "description": "Frequent moderate and High-Intensity exercise can help reduce your risk of heart disease.",
                                },
                            ],
                            "on_schedule": [
                                {
                                    "title": "Great job!",
                                    "description": "You are on the right track to a healthy exercise routine!",
                                },
                            ],
                        },
                    },
                },
                {
                    "focus": "bmi",
                    "goal": "loseWeight",
                    "frequency": 3,
                    "checkpoint": {
                        "prompt": "What is your weight?",
                        "response": {
                            "type": "number",
                            "minimum": 48, 
                            "maximum": 999,
                            "unit": "pounds"
                        },
                        "feedback": {
                            "behind": [
                                {
                                    "title": "Keep at it!",
                                    "description": "Achieving a healthy weight can reduce your risk of heart disease!",
                                },
                            ],
                            "on_schedule": [
                                {
                                    "title": "Great job!",
                                    "description": "You are on the right track to losing 5% of your body weight!",
                                },
                            ],
                        },
                    },
                },
            ],
            "focuses": [
                {
                    "focus": "glucose",
                    "content": [
                        { 
                            "type": "challenge",
                            "day": 0, 
                            "heart": true,
                            "notification": null,                           
							"title": "Time for a FOCUS CHALLENGE for improving your Blood Pressure.  Let’s get started.",
							"body": "This week we will focus on improvements you can make regarding your blood pressure. Blood pressure is simply a measurement of the force exerted against the walls of your arteries as your heart pumps blood to your body. The BEST path to reducing blood pressure is to reduce salt (or sodium) in your diet along with healthy diet and exercise. We want to help you.",
							"url": "http://domain/appName/glucose_challenge.json",
							"response": "Great!  You are going to arm yourself with the information you need to successfully improve your blood pressure!"
                        },
                        { 
                            "type": "video",
                            "day": 0, 
                            "heart": false,
                            "notification": null,
                            "title": "Learn more about the information to follow.  It’s just a couple minutes of your time. ",
                            "body": "Also check out Pat and Allison’s short video.  Get to know Pat and Allison from the AHA. They have some great insights on blood pressure.",
                            "url": "http://careplan.heart.org/videos/glucose/BloodSugar.mp4"
                        },
                        { 
                            "type": "article",
                            "day": 1, 
                            "heart": false,
                            "notification": null,
                            "title": "Let’s talk about blood pressure - We will add some insights to help with the goal of keeping you healthy.  One of the top things to think about is sodium intake. ",
                            "body": "Too much sodium in your system causes your body to retain (hold onto) water. This puts an extra burden on your heart and blood vessels. In some people, this may lead to or raise high blood pressure.  Click this link to learn more. Read today’ article to learn more.",
                            "url":"http://www.heart.org/idc/groups/heart-public/@wcm/@hcm/documents/downloadable/ucm_300625.pdf"
                        },
                        { 
                            "type": "video",
                            "day": 2, 
                            "heart": false,
                            "notification": null,
                            "title": "Blood Pressure at a healthy level has a 2-minute explanation. See the video from Eduardo Sanchez MD, a Medical Director at the American Heart Association.",
                            "body": "",
                            "url": "http://careplan.heart.org/videos/glucose/Eduardo-BloodSugar.mp4"
                        },
                        { 
                            "type": "video",
                            "day": 3, 
                            "heart": true,
                            "notification": null,
                            "title": "This 4 minute video (Managing Blood Pressure) will keep you in total control of your health and life.",
                            "body": "",
                            "url": "http://careplan.heart.org/videos/glucose/OneofLifesSimple7-2017.mp4"
                        },
                        { 
                            "type": "share",
                            "day": 4, 
                            "heart": false,
                            "notification": null,                            
							"title": " A great way to maintain your progress of achieving a healthier low sodium diet is to share what you’ve learned with a family member or friend! ",
							"body": "Eat fewer packaged foods / Remove the salt shaker from the table/ Ask at every meal I eat out “how much salt is in that?” (look for less than 1500 mg). Pass it on!"
   
                        },
                        { 
                            "type": "quiz",
                            "day": 5, 
                            "heart": false,
                            "notification": null,
                            "title": "",
                            "body": "",
                            "url": "http://domain/appName/glucose_quiz.json"
                        },
                        { 
                            "type": "final",
                            "day": 6, 
                            "heart": true,
                            "notification": null,                             
							"title": "Congratulations on getting your hearts towards achieving better Blood Pressure!  It is time to tell us how you did and get the last one!",
							"body": "We trust you learned a lot about our easy-to-use strategies for managing the simple things to have a heart-healthy life.  Remember to go back and look at the tools to get all your hearts.  You need HEARTS to get to the next topic!  So please rate how you did:",
							"options": ["Excellent","Very Good","Good","Fair","Poor"],
							"response": "Thank you again for completing the session on blood pressure.  Now you are now armed with the information you need to successfully improve your blood pressure!"
    
                        } 
                    ]
                }
            ],
            "reengagement_notifications": [
                {
                    "day": 1,
                    "title": "Don't fall behind!",
                    "body": "Open your CarePlan every day to stay on track"
                },
                {
                    "day": 4,
                    "title": "It's not too late!",
                    "body": "Record your latest weight measurement and get back on track"
                },
                {
                    "day": 8,
                    "title": "Resume your CarePlan!",
                    "body": "Open the app to see the latest CarePlan content"
                }
            ]
        }

# Data Structures

## OAuth grant request (object)
+ `grant_type`: `client_credentials` (string, required)